package lv.kotova.ParcelPatronusApp.models.enums;

public enum Status {
    AWAITING_PICKUP,

    ASSIGNED_TO_COURIER_FOR_PICKUP,
    IN_TRANSIT_TO_SORTING_FACILITY,
    UNLOADED_AT_SORTING_FACILITY,
    ACCEPTED_AT_SORTING_FACILITY,

    ASSIGNED_TO_COURIER_FOR_DELIVERY,
    IN_TRANSIT_TO_DESTINATION,

    DELIVERED_TO_DESTINATION_MACHINE,
    COLLECTED_BY_RECIPIENT,

    UNCOLLECTED_PARCEL,
    RETURNED_TO_DELIVERY_BOX,
    RETURNED_TO_SENDER
}
